# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c2e240c6019c9632ae130cae5c35fa742b1175ff1b8e1a3dc653fc9349a2852e584969a7ba8f3c9c72332b1043c25036abcb9266d07297dcf137c5784b6c03c1

test:
  secret_key_base: 1bf22f21b2644bc1aa7910040e885c13abe812d3f1b8adc7a6d5373723f7452182f5cfaa0e472aca95ccde7ba5fd9eddd27dbea2d2a9b672403f72d70a740d5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
